sudo: false
language: c
  
addons:
  apt:
    packages:
    - pandoc
  
#script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh
#after_script: bash release.sh -g 7.3.5
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash
 
branches:
  only:
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/